//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dz42.KlijentAplikacija {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KlijentAplikacija.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name valuta1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konvertervaluta", ReplyAction="*")]
        dz42.KlijentAplikacija.konvertervalutaResponse konvertervaluta(dz42.KlijentAplikacija.konvertervalutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konvertervaluta", ReplyAction="*")]
        System.Threading.Tasks.Task<dz42.KlijentAplikacija.konvertervalutaResponse> konvertervalutaAsync(dz42.KlijentAplikacija.konvertervalutaRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        dz42.KlijentAplikacija.HelloWorldResponse HelloWorld(dz42.KlijentAplikacija.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<dz42.KlijentAplikacija.HelloWorldResponse> HelloWorldAsync(dz42.KlijentAplikacija.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class konvertervalutaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="konvertervaluta", Namespace="http://tempuri.org/", Order=0)]
        public dz42.KlijentAplikacija.konvertervalutaRequestBody Body;
        
        public konvertervalutaRequest() {
        }
        
        public konvertervalutaRequest(dz42.KlijentAplikacija.konvertervalutaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class konvertervalutaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float val;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string valuta2;
        
        public konvertervalutaRequestBody() {
        }
        
        public konvertervalutaRequestBody(float val, string valuta1, string valuta2) {
            this.val = val;
            this.valuta1 = valuta1;
            this.valuta2 = valuta2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class konvertervalutaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="konvertervalutaResponse", Namespace="http://tempuri.org/", Order=0)]
        public dz42.KlijentAplikacija.konvertervalutaResponseBody Body;
        
        public konvertervalutaResponse() {
        }
        
        public konvertervalutaResponse(dz42.KlijentAplikacija.konvertervalutaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class konvertervalutaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float konvertervalutaResult;
        
        public konvertervalutaResponseBody() {
        }
        
        public konvertervalutaResponseBody(float konvertervalutaResult) {
            this.konvertervalutaResult = konvertervalutaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public dz42.KlijentAplikacija.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(dz42.KlijentAplikacija.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public dz42.KlijentAplikacija.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(dz42.KlijentAplikacija.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : dz42.KlijentAplikacija.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<dz42.KlijentAplikacija.WebService1Soap>, dz42.KlijentAplikacija.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dz42.KlijentAplikacija.konvertervalutaResponse dz42.KlijentAplikacija.WebService1Soap.konvertervaluta(dz42.KlijentAplikacija.konvertervalutaRequest request) {
            return base.Channel.konvertervaluta(request);
        }
        
        public float konvertervaluta(float val, string valuta1, string valuta2) {
            dz42.KlijentAplikacija.konvertervalutaRequest inValue = new dz42.KlijentAplikacija.konvertervalutaRequest();
            inValue.Body = new dz42.KlijentAplikacija.konvertervalutaRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta1 = valuta1;
            inValue.Body.valuta2 = valuta2;
            dz42.KlijentAplikacija.konvertervalutaResponse retVal = ((dz42.KlijentAplikacija.WebService1Soap)(this)).konvertervaluta(inValue);
            return retVal.Body.konvertervalutaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dz42.KlijentAplikacija.konvertervalutaResponse> dz42.KlijentAplikacija.WebService1Soap.konvertervalutaAsync(dz42.KlijentAplikacija.konvertervalutaRequest request) {
            return base.Channel.konvertervalutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<dz42.KlijentAplikacija.konvertervalutaResponse> konvertervalutaAsync(float val, string valuta1, string valuta2) {
            dz42.KlijentAplikacija.konvertervalutaRequest inValue = new dz42.KlijentAplikacija.konvertervalutaRequest();
            inValue.Body = new dz42.KlijentAplikacija.konvertervalutaRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta1 = valuta1;
            inValue.Body.valuta2 = valuta2;
            return ((dz42.KlijentAplikacija.WebService1Soap)(this)).konvertervalutaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dz42.KlijentAplikacija.HelloWorldResponse dz42.KlijentAplikacija.WebService1Soap.HelloWorld(dz42.KlijentAplikacija.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            dz42.KlijentAplikacija.HelloWorldRequest inValue = new dz42.KlijentAplikacija.HelloWorldRequest();
            inValue.Body = new dz42.KlijentAplikacija.HelloWorldRequestBody();
            dz42.KlijentAplikacija.HelloWorldResponse retVal = ((dz42.KlijentAplikacija.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dz42.KlijentAplikacija.HelloWorldResponse> dz42.KlijentAplikacija.WebService1Soap.HelloWorldAsync(dz42.KlijentAplikacija.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<dz42.KlijentAplikacija.HelloWorldResponse> HelloWorldAsync() {
            dz42.KlijentAplikacija.HelloWorldRequest inValue = new dz42.KlijentAplikacija.HelloWorldRequest();
            inValue.Body = new dz42.KlijentAplikacija.HelloWorldRequestBody();
            return ((dz42.KlijentAplikacija.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
